name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls
      - name: Simple JavaScript Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Swayam'
      - name: Log Greeting Time
        run: echo "Greeting ${{ steps.greet.outputs.time }}"